### ISSUE TITLE
RPF: Quote cards not loading sometimes

### ISSUE THREAD

**Issue by ashley-cai** [the-pudding/fanfic#21]
unclear what is causing the issue, as I cannot consistently reproduce

<img width="973" alt="Screenshot 2024-09-26 at 1 06 00 AM" src="https://github.com/user-attachments/assets/ca6bf3ad-9d53-4f2c-9863-7e83f6fbdf17">

**Comment by jadiehm** [comment]
I think I fixed this, but I can't recreate it so who knows!
