### ISSUE TITLE
i was seeing a bit gap between the end of canon and RPF and the methodology section

### ISSUE THREAD

**Issue by caitlynmralph** [the-pudding/fanfic#25]
![Screenshot 2024-10-02 at 18 44 12](https://github.com/user-attachments/assets/349de540-c1b5-451e-8133-6fa6ab2e3e6c)
![Screenshot 2024-10-02 at 18 44 23](https://github.com/user-attachments/assets/121c1164-0842-4167-964c-cdfc55d862ce)

**Comment by caitlynmralph** [comment]
i'm on my mac air / chrome / using my monitor

**Comment by jadiehm** [comment]
hacky, but it seems to work. jumps won't be smooth on mobile, because mobile.
